# Generated by Django 5.2.5 on 2025-11-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='csv_filename',
            field=models.CharField(default='unknown.csv', max_length=100),
        ),
    ]
