# Generated by Django 5.2.7 on 2025-12-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subject_csv_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='question_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
