# Generated by Django 5.2.7 on 2025-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_uploadedpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpaper',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_papers/'),
        ),
    ]
