# Generated by Django 5.2.7 on 2025-12-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_uploadedpaper_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedpaper',
            name='college',
        ),
        migrations.RemoveField(
            model_name='uploadedpaper',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadedpaper',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='uploadedpaper',
            name='subject',
        ),
    ]
